name: palakat_monorepo
description: Palakat monorepo workspace containing event notifier apps and backend
publish_to: 'none'

environment:
  sdk: ^3.8.1

workspace:
  - apps/palakat
  - apps/palakat_admin
